name: eco
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  eva_icons_flutter: ^3.1.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: 2.8.7
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
