// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0aB_9hNu0DeXq7QLs8OPyIoVtP5ko28',
    appId: '1:740162070861:web:e98b02030ed76d47212f04',
    messagingSenderId: '740162070861',
    projectId: 'neweco-39308',
    authDomain: 'neweco-39308.firebaseapp.com',
    storageBucket: 'neweco-39308.appspot.com',
    measurementId: 'G-ENQDBW15W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZ2sKFH7QX9B0Hkri1XNzsaq1gn7pxWg',
    appId: '1:740162070861:android:5b152b23b56c2e85212f04',
    messagingSenderId: '740162070861',
    projectId: 'neweco-39308',
    storageBucket: 'neweco-39308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTci-Ww9RrxaG07lsyZqhZG3jkwsjKt0',
    appId: '1:740162070861:ios:5c32b8e317fbbf18212f04',
    messagingSenderId: '740162070861',
    projectId: 'neweco-39308',
    storageBucket: 'neweco-39308.appspot.com',
    iosBundleId: 'com.example.eco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTci-Ww9RrxaG07lsyZqhZG3jkwsjKt0',
    appId: '1:740162070861:ios:5c32b8e317fbbf18212f04',
    messagingSenderId: '740162070861',
    projectId: 'neweco-39308',
    storageBucket: 'neweco-39308.appspot.com',
    iosBundleId: 'com.example.eco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc0aB_9hNu0DeXq7QLs8OPyIoVtP5ko28',
    appId: '1:740162070861:web:00a147bdb14bd84b212f04',
    messagingSenderId: '740162070861',
    projectId: 'neweco-39308',
    authDomain: 'neweco-39308.firebaseapp.com',
    storageBucket: 'neweco-39308.appspot.com',
    measurementId: 'G-QERG2JQ67S',
  );

}